--- 
title: "Exploration de données"
author: "Kouassi M. 2021"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
#bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Contrôle des insectes ravageurs de la tomate"
---

# Présentation du projet selon ma lecture (du projet) à l'issue des 2 soutenances

Impacts des insectes ravageurs sur la croissance et le rendement de la tomate (_Solanum lycopercinum_ L.) sous différentes méthodes de contrôle au carré potager de l’UPGC - Korhogo ; à travers une étude comparée au champ de quatre méthodes de contrôle. (=> tentative de résumé de tout en un !)

## Dispositif expérimental

Blocs complets aléatoires, quatre traitements, 2 répétitions.

Les traitements :

1. T0, le témoin,
1. T1, filet de protection anti-insectes,
1. T2, lutte mécanique,
1. T3, Insecticide Cigogne EC 50.

Donc 8 unités expérimentales (UE) au total, 12 plants espacés de 50 cm sur 3 rangs par UE. Mesures effectuées systématiquement sur 10 plants par UE (et une moyenne est ou sera calculée par plant ou par unité de surface), par UE.


## Objectif général

.. aider l'apprenant à proposer ...

## Objectifs spécifiques

.. aider l'apprenant à proposer ...

## Données collectées

- Le nombre de feuilles présentant des attaques supposées d'insectes

- Quelques catégorisations d'attaques comme :

  - le nombre de feuilles attaquées (va falloir clarifer ce qu'on entend par là), 
  - le nombre de feuilles perforées
  - le nombre de feuilles jaunies, 
  - le nombre de feuilles perforées et jaunies. 


- La sévérité des cas de perforation du type :

  - perforations totalisant 1 à 5 trous, 
  - perforations totalisant plus de 6 trous. 

- La croissance en hauteur des plants.

- Le nombre de fruits récoltés

- Et, le rendement (masse de tomate récoltée par unité de surface).

Collecte réalisée durant quatre semaines pour certaines variables.

## Méthodes d'analyses

Colecte et organisation des données en Excel, figures en Excel.

Test du Khi-2 pour les décomptes avec ...

ANOVA pour les variables quantitatives continues avec ....

Lorsque différence significative ... tests post-hoc de comparaisons multiples par paires avec :

- fonction `emmeans()` du package du même nom, qui utilise la méthode de Tuckey, à la suite du Chi-2
- SNK ou un équivalant non paramétrique pour la hauteur des plants et le rendement.


## Les librairies

J'ai fait mes analyses en R version .....

Ces calculs ont nécessité l'utilisation des packages (modules ou librairies) suivant.es :

```{r message=FALSE, warning=FALSE}
library("ggpubr")    # ggqqplot()
library("agricolae") # SNK.test()
library("car")       # levene_test()
library("rstatix")   # identify_outliers()
library("Rmisc")     # summarySE()
library("emmeans")   # emmeans()
library("multcomp")  # cld()
library("tidyverse") # dplyr, ggplot2
```

Les chapitres suivant donnent les détails des analyses effectuées.


## Thèmes de stage

Koffi Amoin Marina

> **Impacts des insectes ravageurs sur la tomate (*Solanum lycopercicum* L.) sous différentes méthodes de contrôle au carré potager de l’UPGC - Korhogo**.

Diambla Bi Vanie Esai Monami

> **Effet de différentes méthodes de contrôle des insectes ravageurs sur la croissance et le rendement de la tomate (*Solanum lycopercicum* L.) au carré potager de l’UPGC - Korhogo**.


## Quelques remarques

J'ai exploré les données sans ténir compte de pourquoi vous avez choisi de mesurer telle ou telle variable (beaucoup plus *défense des cultures*). 

Pour le nombre de trous dans les feuilles, j'ai regroupé les deux dernières catégories : 6 à 10 trous, et 10 trous et plus, en **6 trous et plus**. Il y avait trop de zéros. Malgré ce regroupement, il y a encore des zéros surtout dans la catégorie 6 trous et plus. Ce qui est incompatible avec les principes d'utilisation du Khi-2.

L'étudiante pourrait seulement présenter les variables au chapitres 2, 3, 6 et 7.

M. Diambla, les chapitres suivants.



**ZC.**













